"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isBelowMinSupported = exports.isUpdateAvailable = exports.compareSemver = exports.normalizeErrorMessage = exports.formatCurrency = exports.escapeHtml = exports.buildPdfFileName = exports.formatOfferNumberForFile = exports.pickShorter = exports.sanitizeFilePart = exports.ROLES = exports.normalizeRoleRbac = exports.canUseSalesFeatures = exports.canViewReports = exports.canManageSystemSettings = exports.canManageUsers = exports.canAccessAdminPanel = exports.OUTBOX_OPERATION_TYPES = exports.EMAIL_HISTORY_STATUSES = exports.USER_ROLES = exports.OFFER_STATUSES = exports.SCHEMA_SQL = exports.getCyberFolksSmtpDefaults = exports.sendMailWithCredentials = exports.CREDENTIAL_SERVICE = exports.mergePdfEditorContent = exports.DEFAULT_PDF_EDITOR_PAGE2 = exports.DEFAULT_PDF_EDITOR_PAGE1 = exports.DEFAULT_PDF_EDITOR_CONTENT = exports.generatePdf = exports.mergePdfTemplateConfig = exports.DEFAULT_ELEMENT_POSITIONS = exports.DEFAULT_PDF_TEMPLATE_CONFIG = exports.renderOfferHtml = exports.heightInRange = exports.parseHeightCondition = exports.normalizeJednostka = exports.toInt = exports.toNumber = exports.runPricingSelfTest = exports.calculatePrice = exports.generateOutboxId = exports.flushOutbox = exports.syncPricingIfNewer = exports.ApiClient = void 0;
var client_1 = require("./api/client");
Object.defineProperty(exports, "ApiClient", { enumerable: true, get: function () { return client_1.ApiClient; } });
var pricingSync_1 = require("./sync/pricingSync");
Object.defineProperty(exports, "syncPricingIfNewer", { enumerable: true, get: function () { return pricingSync_1.syncPricingIfNewer; } });
var outbox_1 = require("./sync/outbox");
Object.defineProperty(exports, "flushOutbox", { enumerable: true, get: function () { return outbox_1.flushOutbox; } });
Object.defineProperty(exports, "generateOutboxId", { enumerable: true, get: function () { return outbox_1.generateOutboxId; } });
var pricingEngine_1 = require("./pricing/pricingEngine");
Object.defineProperty(exports, "calculatePrice", { enumerable: true, get: function () { return pricingEngine_1.calculatePrice; } });
Object.defineProperty(exports, "runPricingSelfTest", { enumerable: true, get: function () { return pricingEngine_1.runPricingSelfTest; } });
var normalize_1 = require("./pricing/normalize");
Object.defineProperty(exports, "toNumber", { enumerable: true, get: function () { return normalize_1.toNumber; } });
Object.defineProperty(exports, "toInt", { enumerable: true, get: function () { return normalize_1.toInt; } });
Object.defineProperty(exports, "normalizeJednostka", { enumerable: true, get: function () { return normalize_1.normalizeJednostka; } });
var parseHeightCondition_1 = require("./pricing/parseHeightCondition");
Object.defineProperty(exports, "parseHeightCondition", { enumerable: true, get: function () { return parseHeightCondition_1.parseHeightCondition; } });
Object.defineProperty(exports, "heightInRange", { enumerable: true, get: function () { return parseHeightCondition_1.heightInRange; } });
var template_1 = require("./pdf/template");
Object.defineProperty(exports, "renderOfferHtml", { enumerable: true, get: function () { return template_1.renderOfferHtml; } });
var templateConfig_1 = require("./pdf/templateConfig");
Object.defineProperty(exports, "DEFAULT_PDF_TEMPLATE_CONFIG", { enumerable: true, get: function () { return templateConfig_1.DEFAULT_PDF_TEMPLATE_CONFIG; } });
Object.defineProperty(exports, "DEFAULT_ELEMENT_POSITIONS", { enumerable: true, get: function () { return templateConfig_1.DEFAULT_ELEMENT_POSITIONS; } });
Object.defineProperty(exports, "mergePdfTemplateConfig", { enumerable: true, get: function () { return templateConfig_1.mergePdfTemplateConfig; } });
var generator_1 = require("./pdf/generator");
Object.defineProperty(exports, "generatePdf", { enumerable: true, get: function () { return generator_1.generatePdf; } });
var editorContent_1 = require("./pdf/editorContent");
Object.defineProperty(exports, "DEFAULT_PDF_EDITOR_CONTENT", { enumerable: true, get: function () { return editorContent_1.DEFAULT_PDF_EDITOR_CONTENT; } });
Object.defineProperty(exports, "DEFAULT_PDF_EDITOR_PAGE1", { enumerable: true, get: function () { return editorContent_1.DEFAULT_PDF_EDITOR_PAGE1; } });
Object.defineProperty(exports, "DEFAULT_PDF_EDITOR_PAGE2", { enumerable: true, get: function () { return editorContent_1.DEFAULT_PDF_EDITOR_PAGE2; } });
Object.defineProperty(exports, "mergePdfEditorContent", { enumerable: true, get: function () { return editorContent_1.mergePdfEditorContent; } });
var credentials_1 = require("./email/credentials");
Object.defineProperty(exports, "CREDENTIAL_SERVICE", { enumerable: true, get: function () { return credentials_1.CREDENTIAL_SERVICE; } });
var smtpSender_1 = require("./email/smtpSender");
Object.defineProperty(exports, "sendMailWithCredentials", { enumerable: true, get: function () { return smtpSender_1.sendMailWithCredentials; } });
Object.defineProperty(exports, "getCyberFolksSmtpDefaults", { enumerable: true, get: function () { return smtpSender_1.getCyberFolksSmtpDefaults; } });
var schema_1 = require("./db/schema");
Object.defineProperty(exports, "SCHEMA_SQL", { enumerable: true, get: function () { return schema_1.SCHEMA_SQL; } });
var constants_1 = require("./constants");
Object.defineProperty(exports, "OFFER_STATUSES", { enumerable: true, get: function () { return constants_1.OFFER_STATUSES; } });
Object.defineProperty(exports, "USER_ROLES", { enumerable: true, get: function () { return constants_1.USER_ROLES; } });
Object.defineProperty(exports, "EMAIL_HISTORY_STATUSES", { enumerable: true, get: function () { return constants_1.EMAIL_HISTORY_STATUSES; } });
Object.defineProperty(exports, "OUTBOX_OPERATION_TYPES", { enumerable: true, get: function () { return constants_1.OUTBOX_OPERATION_TYPES; } });
var rbac_1 = require("./rbac");
Object.defineProperty(exports, "canAccessAdminPanel", { enumerable: true, get: function () { return rbac_1.canAccessAdminPanel; } });
Object.defineProperty(exports, "canManageUsers", { enumerable: true, get: function () { return rbac_1.canManageUsers; } });
Object.defineProperty(exports, "canManageSystemSettings", { enumerable: true, get: function () { return rbac_1.canManageSystemSettings; } });
Object.defineProperty(exports, "canViewReports", { enumerable: true, get: function () { return rbac_1.canViewReports; } });
Object.defineProperty(exports, "canUseSalesFeatures", { enumerable: true, get: function () { return rbac_1.canUseSalesFeatures; } });
Object.defineProperty(exports, "normalizeRoleRbac", { enumerable: true, get: function () { return rbac_1.normalizeRole; } });
Object.defineProperty(exports, "ROLES", { enumerable: true, get: function () { return rbac_1.ROLES; } });
var pdfFileName_1 = require("./utils/pdfFileName");
Object.defineProperty(exports, "sanitizeFilePart", { enumerable: true, get: function () { return pdfFileName_1.sanitizeFilePart; } });
Object.defineProperty(exports, "pickShorter", { enumerable: true, get: function () { return pdfFileName_1.pickShorter; } });
Object.defineProperty(exports, "formatOfferNumberForFile", { enumerable: true, get: function () { return pdfFileName_1.formatOfferNumberForFile; } });
Object.defineProperty(exports, "buildPdfFileName", { enumerable: true, get: function () { return pdfFileName_1.buildPdfFileName; } });
var format_1 = require("./utils/format");
Object.defineProperty(exports, "escapeHtml", { enumerable: true, get: function () { return format_1.escapeHtml; } });
Object.defineProperty(exports, "formatCurrency", { enumerable: true, get: function () { return format_1.formatCurrency; } });
var errorMessage_1 = require("./utils/errorMessage");
Object.defineProperty(exports, "normalizeErrorMessage", { enumerable: true, get: function () { return errorMessage_1.normalizeErrorMessage; } });
var semver_1 = require("./utils/semver");
Object.defineProperty(exports, "compareSemver", { enumerable: true, get: function () { return semver_1.compareSemver; } });
Object.defineProperty(exports, "isUpdateAvailable", { enumerable: true, get: function () { return semver_1.isUpdateAvailable; } });
Object.defineProperty(exports, "isBelowMinSupported", { enumerable: true, get: function () { return semver_1.isBelowMinSupported; } });
